name: build site

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest # Run on same os and hardware

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x # 
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
